# -*- coding: utf-8 -*-
"""09. Prueba Hugo Morales : Análisis exploratorio de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17JYZf-48CHd6tDEiXaSESYWI6DzRCGEX

#09. Prueba: Análisis exploratorio de datos
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# --- CARGA DEL DATAFRAME ---
# Instrucción: Carga el DataFrame de videojuegos.csv
df = pd.read_csv('09. videojuegos.csv')
df.info()
df.head()

# =============================================================================
# PARTE 1: ANÁLISIS VISUAL CON SEABORN (6 Puntos)
# =============================================================================

# 1. Gráfico de Pares (pairplot): (2 Puntos)
# Requerimiento: Relación entre variables numéricas y diferenciar por Plataforma (hue).
# Esto revela si las relaciones ventas/puntajes varían según la marca.
vars_num = ['Ventas_NA', 'Ventas_EU', 'Ventas_JP', 'Critica_Puntaje']
sns.pairplot(df, vars=vars_num, hue='Plataforma', palette='viridis')
plt.show()
print()
print("-------===========================================================-------")
print("El análisis de dispersión muestra una alta heterogeneidad en todos los")
print("mercados; ninguna plataforma presenta una ventaja competitiva clara en ")
print("volumen de ventas por región en este dataset. Se confirma la nula ")
print("dependencia entre la calificación de la crítica y el éxito comercial, ya que los ")
print("títulos se distribuyen uniformemente sin importar su puntaje")

# 2. Gráfico de Violín (violinplot):
# Requerimiento: Distribución de Critica_Puntaje por Plataforma (densidad y rangos).
# Interpretación: La "forma" del violín indica la densidad y el largo indica el rango.
plt.figure(figsize=(10, 6))
sns.violinplot(data=df, x='Plataforma', y='Critica_Puntaje', inner='quartile')
plt.title('Análisis de Densidad y Rangos de Calidad por Plataforma')
plt.show()
print()
print("-------===========================================================-------")

print("PC y PlayStation muestran alta volatilidad; su dispersión indica que la calidad ")
print("no está estandarizada. Nintendo es el mercado más seguro, con mayor ")
print("densidad de títulos en rangos de puntaje altos. A mayor dispersión (violines ")
print("más largos), mayor riesgo de inversión por falta de consistencia")

# 3. Mapa de Calor (heatmap):
# Requerimiento: Matriz de correlación y mostrar valores (annot=True) para interpretar.
matriz_corr = df[vars_num].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(matriz_corr, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matriz de Correlación: Ventas y Puntajes')
plt.show()
# Interpretación: Los números permiten identificar rápidamente qué mercados
# están más correlacionados entre sí.
print()
print("-------===========================================================-------")
print("La matriz revela mercados desconectados: la correlación NA-EU es de -0.20,")
print("indicando que no son espejos. Japón es el más independiente (-0.02 vs NA),")
print("confirmando gustos únicos. Además, el puntaje de la crítica (0.04) no ")
print("garantiza ventas; el éxito comercial es independiente de la critica.")

# =============================================================================
# PARTE 2: PERSONALIZACIÓN DE GRÁFICOS CON MATPLOTLIB
# =============================================================================

# 4. Preparación de Datos:
# ● Calcula el total de ventas globales para cada juego.
df['Ventas_Globales'] = df['Ventas_NA'] + df['Ventas_EU'] + df['Ventas_JP']

# ● Agrupa por Género y calcula la media de Ventas_Globales.
ventas_por_genero = df.groupby('Genero')['Ventas_Globales'].mean().reset_index()

# 5 y 6. Creación y Personalización del Gráfico de Barras:
# Se utiliza el modelo orientado a objetos.
fig, ax = plt.subplots(figsize=(12, 7))

# Requerimientos: Color steelblue y Borde negro.
barras = ax.bar(ventas_por_genero['Genero'],
                ventas_por_genero['Ventas_Globales'],
                color='steelblue',
                edgecolor='black')

# Requerimiento Punto 5: Título descriptivo y etiquetas claras.
ax.set_title('Promedio de Ventas Globales por Género de Videojuego', fontsize=14)
ax.set_xlabel('Género del Videojuego', fontsize=12)
ax.set_ylabel('Ventas Globales Promedio (Millones)', fontsize=12)

# Requerimiento Punto 6: Fija límites del eje Y (0 a max + espacio visual).
max_val = ventas_por_genero['Ventas_Globales'].max()
ax.set_ylim(0, max_val * 1.15)

# Requerimiento Punto 6: Añade anotaciones de texto sobre cada barra (valor exacto).
for barra in barras:
    yval = barra.get_height()
    ax.text(barra.get_x() + barra.get_width()/2, yval + (max_val * 0.01),
            f'{yval:.2f}', ha='center', va='bottom', fontweight='bold')

# Requerimiento Punto 6: Guarda el gráfico final con el nombre solicitado.
plt.tight_layout()
fig.savefig('ventas_por_genero_personalizado.png')

plt.show()